version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/"
    labels:
      - "pr: dependency-update"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 10
    ignore:
      # Dependabot should not update Home Assistant as that should match the homeassistant key in hacs.json
      - dependency-name: "homeassistant"