repos:
  - repo: local
    hooks:
      - id: codespell
        name: Check code for common misspellings
        language: system
        types: [text]
        stages: [commit-msg, post-commit, manual]
        entry: codespell
        args:
          - --quiet-level=2
          - --ignore-words-list=hass,ba,fo
          - --skip=tests/fixtures/*,custom_components/garmin_connect/translations/*

      - id: pyupgrade
        name: Run pyupgrade
        language: system
        types: [text]
        stages: [commit-msg, post-commit, manual]
        entry: pyupgrade
        files: ^.*.py$
        args:
          - "--py311-plus"

      - id: ruff-check
        name: Run ruff check
        language: system
        types: [text]
        stages: [commit-msg, post-commit, manual]
        entry: ruff
        args:
          - check
        files: ^((action|custom_components|script|tests)/.+)?[^/]+\.py$

      - id: mypy
        name: Run mypy type checker
        language: system
        types: [python]
        stages: [commit-msg, post-commit, manual]
        entry: mypy
        args:
          - --ignore-missing-imports
          - --check-untyped-defs
        files: ^custom_components/.+\.py$

      - id: check-yaml
        name: Check YAML files
        language: system
        types: [yaml]
        stages: [commit-msg, post-commit, manual]
        entry: check-yaml
        args:
          - --unsafe

      - id: check-executables-have-shebangs
        name: Check that executables have shebangs
        language: system
        types: [text, executable]
        entry: check-executables-have-shebangs
        stages: [commit-msg, post-commit, manual]

      - id: check-json
        name: Check JSON files
        language: system
        types: [json]
        stages: [commit-msg, post-commit, manual]
        entry: check-json

      - id: requirements-txt-fixer
        name: Check requirements files
        language: system
        types: [text]
        stages: [commit-msg, post-commit, manual]
        entry: requirements-txt-fixer
        files: ^requirements_.*.txt$

      - id: check-ast
        name: Check Python AST
        language: system
        types: [python]
        stages: [commit-msg, post-commit, manual]
        entry: check-ast

      - id: mixed-line-ending
        name: Check line endings
        language: system
        types: [text]
        stages: [commit-msg, post-commit, manual]
        entry: mixed-line-ending
        args:
          - --fix=lf

