name: Test hassfest

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: hassfest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Test hassfest
        uses: ./hassfest
